sudo: required
language: c
dist: xenial

matrix:
  include:
     - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - build-essential autoconf autotools-dev libtool
            - cmake libudev-dev libavahi-compat-libdnssd-dev
            - libusb-1.0-0-dev fxload libcurl4-gnutls-dev
            - libgphoto2-dev git curl
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

     - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - build-essential autoconf autotools-dev libtool
            - cmake libudev-dev libavahi-compat-libdnssd-dev
            - libusb-1.0-0-dev fxload libcurl4-gnutls-dev
            - libgphoto2-dev git curl
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

     - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - build-essential autoconf autotools-dev libtool
            - cmake libudev-dev libavahi-compat-libdnssd-dev
            - libusb-1.0-0-dev fxload libcurl4-gnutls-dev
            - libgphoto2-dev git curl
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

     - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - build-essential autoconf autotools-dev libtool
            - cmake libudev-dev libavahi-compat-libdnssd-dev
            - libusb-1.0-0-dev fxload libcurl4-gnutls-dev
            - libgphoto2-dev git curl
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script: make
